# Generated by Django 5.0.7 on 2025-01-09 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_additionalfee_class_fee_alter_fees_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='class_target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='grade_target',
        ),
        migrations.AddField(
            model_name='notification',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='core.class'),
        ),
        migrations.AddField(
            model_name='notification',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='core.grade'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scope',
            field=models.CharField(choices=[('School', 'Entire School'), ('Admin', 'Admins'), ('Staff', 'Staff'), ('Teacher', 'Teachers'), ('Student', 'Students'), ('Grade', 'Grade-level'), ('Class', 'Class-level'), ('Personal', 'Personal')], default='School', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
