# Generated by Django 5.0.7 on 2025-01-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notification_class_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='class_target',
            field=models.ManyToManyField(blank=True, related_name='notifications_for_class', to='core.class'),
        ),
        migrations.AddField(
            model_name='notification',
            name='grade_target',
            field=models.ManyToManyField(blank=True, related_name='notifications_for_grade', to='core.grade'),
        ),
        migrations.AddField(
            model_name='notification',
            name='personal_recipients',
            field=models.ManyToManyField(blank=True, related_name='personal_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scope',
            field=models.CharField(choices=[('School', 'Entire School'), ('Grade', 'Grade-level'), ('Class', 'Specific Class'), ('Personal', 'Personal'), ('Admin', 'Admins'), ('Staff', 'Staff'), ('Teacher', 'Teachers'), ('Student', 'Students')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
