# Generated by Django 5.0.7 on 2025-01-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_notification_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(blank=True, choices=[('1st Section', '1st Section'), ('2nd Section', '2nd Section'), ('3rd Section', '3rd Section'), ('4th Section', '4th Section')], max_length=20, null=True),
        ),
    ]
