# Generated by Django 5.0.7 on 2025-01-28 19:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_class_instance_attendance_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_instance', 'section', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent_students',
            field=models.ManyToManyField(blank=True, related_name='absent_attendance', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 28, 19, 46, 46, 556342, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_students',
            field=models.ManyToManyField(blank=True, related_name='present_attendance', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.CharField(choices=[('1st Section', '1st Section'), ('2nd Section', '2nd Section'), ('3rd Section', '3rd Section'), ('4th Section', '4th Section')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
