# Generated by Django 5.0.7 on 2025-01-30 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('name', 'subject', 'grade', 'academic_year'), name='unique_exam_per_subject_grade_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='examgrade',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam_grade'),
        ),
    ]
