# Generated by Django 5.0.7 on 2025-01-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exam_grade_alter_examgrade_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='exam',
            name='classes_assigned',
            field=models.ManyToManyField(blank=True, related_name='exams', to='core.class'),
        ),
    ]
