# Generated by Django 5.0.7 on 2025-02-05 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_exam_class_assigned_exam_classes_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='class_target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='grade_target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='personal_recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
